# 项目相关配置
jk:
  # 名称
  name: jk-zb
  # 版本
  version: 3.1.4

# 开发环境配置
server:
  # 服务域名
#  host: www.xizinet.com
  # 服务端口
  port: 16000
  servlet:
    # 项目contextPath
    context-path: /${jk.name}
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

#spring 配置文件
spring:
  profiles:
    active: dev